### ISSUE TITLE
Unable to import library

### ISSUE THREAD

**Issue by rafaljanwojcik** [ZILiAT-NASK/StyloMetrix#1]
Hello,
I tried using your library for the first time (version 0.1.7), and I experienced issues with importing the module stylo_metrix. When trying to import your library, I got following error:
`ImportError: cannot import name 'log_incidence' from 'stylo_metrix.utils' (/Users/rafalwojcik/miniconda3/lib/python3.9/site-packages/stylo_metrix/utils.py)`
I checked `utils.py` file and it doesn't contain `log_incidence` function, which was added to `lexical_en.py` file imports in version 0.1.7

**Comment by TomekPro** [comment]
The same for me. Any plans to fix it?

**Comment by ZILiAT-NASK** [comment]
We will soon release version 0.1.8, in which the identified issue will be resolved.

**Comment by ZILiAT-NASK** [comment]
Actually problem already solved. Enjoy!
