### ISSUE TITLE
Convert dictionaries.py from Python to text files

### ISSUE THREAD

**Issue by tomaszklim** [ZILiAT-NASK/StyloMetrix#2]
Regarding this file:
https://github.com/ZILiAT-NASK/StyloMetrix/blob/v0.1.0/src/stylo_metrix/metrics/pl/data/dictionaries.py

It is compatible only with Python and require manual conversion to use these dictionaries from other languages.

I request converting these dictionaries from Python include file, to separate text files - just as it is done for english dictionaries:
https://github.com/ZILiAT-NASK/StyloMetrix/tree/v0.1.0/src/stylo_metrix/metrics/en/data/hurtlex

**Comment by ZILiAT-NASK** [comment]
Thanks for your suggestion. 
Now dictionaries are available in txt extension as well. You can find it here: https://github.com/ZILiAT-NASK/StyloMetrix/tree/v0.1.0/src/stylo_metrix/metrics/pl/data/dictionaries
